exp_name: Bi-Causal


# -- Dataset settings
dataset_name: volleyball
dataset_dir: /home/nfs/zyl/dataset/volleyball
olympic_split: False
joints_folder_name: joints
tracklets_file_name: tracks_normalized.pkl
person_action_label_file_name: tracks_normalized_with_person_action_label.pkl
ball_trajectory_folder_name: volleyball_ball_annotation
joint_graph_path: /home/nfs/zyl/code/GAR/Bi-Causal/models/joint_graph.txt
ball_trajectory_use: True

horizontal_flip_augment: True
horizontal_flip_augment_purturb: True
horizontal_move_augment: True
horizontal_move_augment_purturb: True
vertical_move_augment: True
vertical_move_augment_purturb: True
agent_dropout_augment: True

image_h: 720
image_w: 1280
num_classes: 8
num_person_action_classes: 10
frame_start_idx: 5
frame_end_idx: 14
frame_sampling: 1
N: 12 
J: 17
T: 10
recollect_stats_train: True


# -- Training settings
seed: 16
batch_size: 128
num_epochs: 100
num_workers: 16
optimizer: 'adam'
learning_rate: 0.0005
weight_decay: 0.001


# -- Learning objective settings
loss_coe_relation: 2
loss_coe_inter: 2
loss_coe_group: 2
loss_coe_last_TNT: 3
loss_coe_person: 1
use_group_activity_weights: False
use_person_action_weights: False


# -- Contrastive cluster assignment
nmb_prototypes: 500
temperature: 0.1
sinkhorn_iterations: 3
loss_coe_constrastive_clustering: 0.5


# -- Model settings
model_type: bi-causal
group_person_frame_idx: 5
joint_initial_feat_dim: 8
joint_wo_coords_dim: 2
num_gcn_layers: 3
max_num_tokens: 10
max_times_embed: 100
time_position_embedding_type: absolute_learned_1D 
max_image_positions_h: 1000
max_image_positions_w: 1500
image_position_embedding_type: learned_fourier_2D
# ------ Multiscale Transformer settings
projection_batchnorm: False
projection_dropout: 0.3
hidden_dim: 512
trans_layers: 2
innerTx_nhead: 8
innerTx_dim_feedforward: 1024
innerTx_dropout: 0.5
innerTx_activation: relu 
middleTx_nhead: 8
middleTx_dim_feedforward: 1024
middleTx_dropout: 0.3
middleTx_activation: relu 
outerTx_nhead: 8
outerTx_dim_feedforward: 1024
outerTx_dropout: 0.3
outerTx_activation: relu 
groupTx_nhead: 8
groupTx_dim_feedforward: 1024
groupTx_dropout: 0.2
groupTx_activation: relu 
# ------ Final classifier settings
classifier_use_batchnorm: true
classifier_dropout: 0



# -- Runtime settings
gpu:
  - 0
#  - 1
#   - 2
#   - 3
#   - 4
#   - 5
#   - 6
#   - 7
dev: 0
  
# -- Output settings
checkpoint_dir: ./checkpoints/
log_dir: ./logs/

